### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}




### 1. 게시글 목록 조회
GET http://localhost:8080/api/prompts


### 2. 게시글 등록
POST http://localhost:8080/api/prompts?userId=2
Content-Type: application/json

{
  "title": "테스트 제목",
  "content": "테스트 내용",
  "preview": "미리보기 내용",
  "thumbnailUrl": "https://example.com/test.png",
  "price": 1000,
  "category": "BACKEND",
  "aiType": "GPT4"
}

### 3. 상세 조회
GET http://localhost:8080/api/prompts/4


### 4. 수정
PUT http://localhost:8080/api/prompts/4?userId=2
Content-Type: application/json

{
  "title": "수정된 제목",
  "content": "수정된 내용",
  "preview": "수정된 미리보기",
  "thumbnailUrl": "https://example.com/updated.png",
  "price": 2000,
  "category": "BACKEND",
  "aiType": "GPT4"
}

### 5. 수정 확인
GET http://localhost:8080/api/prompts/4

### 6. 삭제
DELETE http://localhost:8080/api/prompts/4?userId=2

### 7. 삭제 후 조회 확인
GET http://localhost:8080/api/prompts/4